### PR TITLE
Update Dialog.js

### PR DESCRIPTION
**Pull request by Cooookie**
Bug fix (remove excess isPoppedUp check): can't close non-modal window

### CODE REVIEW

**Comment by Cooookie** [comment]
Hello.
There's check in `isPoppedUp` method in `Sim.js`. 
```javascript
this.barrierStack.contains( node )
``` 
For non-modal dialog this condition is never true.

**Comment by samreid** [comment]
Hello @Cooookie, thanks for identifying this problem and submitting a solution.  I'm also seeing other odd behavior related to the popups.  For instance, Sim.js has this method:

```js
    /**
     * Returns true if the node is currently on the barrier stack, and thus 'popped up', and false if not.
     * @param node
     * @public
     */
    isPoppedUp: function( node ) {
      assert && assert( node );
      return this.barrierStack.contains( node );
    }
```

But this really is only checking whether a *model* dialog is popped up--this seems related to the problem you are solving.  Perhaps we should fix the logic in this method rather than omit the check for whether a dialog is popped up?  Or if the behavior in this method is correct, then perhaps it should be renamed.

I'll assign this to myself for further investigation, but please @pixelzoom @jbphet @jonathanolson or @jessegreenberg please chime in if you have suggestions here.

**Comment by samreid** [comment]
By the way, this problem is easy to reproduce by launching the joist dialog demo http://localhost/joist/joist_en.html then clicking "non-modal dialog".

**Comment by samreid** [comment]
We are going to pursue the fix identified in https://github.com/phetsims/joist/issues/314, thanks again for bringing this problem to my attention @Cooookie!

**Comment by pixelzoom** [comment]
A couple of comments related to this:

(1) There are many known problems with non-modal dialogs, see https://github.com/phetsims/joist/issues/293 and https://github.com/phetsims/joist/issues/292. 

(2) Before people outside of PhET start using dialogs, perhaps the base type should be moved to sun, see https://github.com/phetsims/joist/issues/315.

**Comment by ariel-phet** [comment]
@Cooookie by the way, I just sent you an email (to I believe your correct address)

>Hello,

>I believe you are the user "Cooookie" on github. You recently suggested a bug fix for one of our libraries. As an open source project, we are generally curious how people are using our libraries. Mind letting us know how you came across joist and if you were using it for any of your own projects?

>Thanks!

**Comment by Cooookie** [comment]
@ariel-phet oh, hi! 

I'm really sorry for silence, I didn't get a chance to see that email neither GitHub notification (it seems old email account on Github profile, but now I update this info). 
We use PHET libs for some physical simulations (its main purpose I guess). So it's nothing special, but works like charm. So anyway thank your for your work, guys!

**Comment by ariel-phet** [comment]
@Cooookie do you have links to any of the simulations you have built? We would love to see what other people are doing with our libraries!

**Comment by Cooookie** [comment]
@ariel-phet i'm afraid it's not for public use but I'll ask about it.

**Comment by ariel-phet** [comment]
Thanks @Cooookie - or perhaps a skype call or such where you could share your screen and just show me? Our team is just generally interested if people are finding PhET libraries useful

**Comment by Cooookie** [comment]
@ariel-phet 
I doubt we can arrange that as we have strict rules. 
Anyway you have my word as developer - PhET libraries are extremely helpful. Amount of ready components are impressive. For simple simulations you don't event have to actually code.

**Pull request closed without merging**
